### ISSUE TITLE
Link to a channel in Chick's response in DM is broken

### ISSUE THREAD

**Issue by dariagrudzien** [juniorguru/juniorguru-chick#24]
I've chatted to the Chick:

<img width="680" alt="image" src="https://github.com/juniorguru/juniorguru-chick/assets/27728733/1d2b6ea3-b5bb-4d12-854c-2f038187ba4b">

And upon clicking:

<img width="433" alt="image" src="https://github.com/juniorguru/juniorguru-chick/assets/27728733/2785986d-ae02-4f2e-9652-16bb64fba805">

Since we've verified that the channel ID is correct, I wonder whether it's a permissions issue of some sorts @honzajavorek ?

https://github.com/juniorguru/juniorguru-chick/blob/main/juniorguru_chick/bot.py#L35

**Comment by honzajavorek** [comment]
I didn't realize it's not so straightforward to make links to channels in the Discord DMs. Unlike on Slack, the DMs are detached from any servers, thus by default have no server context. I'll think and experiment what would be the best solution.
