### ISSUE TITLE
Remove reaction lines from the codebase

### ISSUE THREAD

**Issue by honzajavorek** [juniorguru/juniorguru-chick#3]
We won't be adding reactions to the messages in #past-vedle-pasti and #můj-dnešní-objev. We can delete these lines:

https://github.com/juniorguru/juniorguru-chick/blob/9c3109f07d6cd180094812be7ee2f9459eec3c76/juniorguru_chick/bot.py#L58

https://github.com/juniorguru/juniorguru-chick/blob/9c3109f07d6cd180094812be7ee2f9459eec3c76/juniorguru_chick/bot.py#L69

Would you, @Mandlemankiller, try to do this change and send it as a Pull Request to this repo? It is a nice opportunity to have first real collaboration here.

**Comment by Mandlemankiller** [comment]
Fixed by #6
